### ISSUE TITLE
No pixel values in image preview

### ISSUE THREAD

**Issue by gerritvanaaken** [nikosch/ProcessWireImageLink#5]
The physical pixel size of the linked image is rather confusing for content editors. They should not be bothered with pixel sizes too much, because we have responsive websites now. It’s the template maker who should care about getting the correctly sized version of the image.

![Example](http://show.praegnanz.de/pic_2016-08-25_94gog.png)

**Comment by nikosch** [comment]
I see your point, but I use ImageLink e.g. in combination with repeaters to set the the picture element for responsive images where I can use different sizes and croppings for different viewports. 

Besides the pixel marker gives me informations about the chosen image, sizing und cropping, that I can't identify in thumbnail view (which crops images to a 1:1 scaling).

**Comment by gerritvanaaken** [comment]
Nevermind, I’ll just write some custom CSS for the backend and hide this.
