### ISSUE TITLE
On-the-fly image uploads are not be saved properly

### ISSUE THREAD

**Issue by gerritvanaaken** [nikosch/ProcessWireImageLink#6]
If you decide to spontaneously upload an image within the image picker, the upload will not exactly fail, but the page that holds the image physically is somehow not saved properly and will not really know about its added images.

**Comment by nikosch** [comment]
I'm not quite sure, but I think this is a problem with the image management itself. I noticed the same effect by uploading images inside the rich text editor image management.

**Comment by gerritvanaaken** [comment]
Interesting – maybe a PW 3 issue, which is not resolved.

**Comment by gerritvanaaken** [comment]
Ich have posted two issues which are responsible for that!

https://github.com/processwire/processwire-issues/issues/41
https://github.com/processwire/processwire-issues/issues/42

**Comment by gerritvanaaken** [comment]
Ryan provided a core fix für on-the-fly uploading.
